version: '3'
services:

  wololo-backend:
    image: facuhump2/wololo-react_wololo-backend
    container_name: wololo-backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - back-end
      - db
    environment:
      - SPRING_DATA_MONGODB_HOST=localhost
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=wololo-tacs
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: us-west-2
        awslogs-stream-prefix: web
  wololo-frontend:
    image: maxfeldman/wololo_frontend:1.0
    container_name: wololo-frontend
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    depends_on:
      - wololo-si
      - wololo-backend
    ports:
      - 80:80
    networks:
      - back-end
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ENV=production
      - REACT_APP_API_URL=localhost
      - REACT_APP_API_PORT=8080
      - REACT_APP_SOCKET_PORT=8082
      - REACT_APP_MAPS_KEY=pk.eyJ1IjoidGVvbm5uIiwiYSI6ImNrZzAwY3RoMjBqbHAydXBpMHFyeXQ2bjYifQ.aZZR74OETObsUi2tCtNbWg
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: us-west-2
        awslogs-stream-prefix: web
  wololo-si:
    image: facuhump2/wololo-si
    container_name: wololo-si
    ports:
      - 8082:8082
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: us-west-2
        awslogs-stream-prefix: web
  mongodb:
    image: 'mongo'
    container_name: 'mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=wololo-tacs
    ports:
      - '27017-27019:27017-27019'
    networks:
      - db

networks:
  db:
  # front-end: quizas despues la necesitemos para la interaccion con el usuario
  back-end:
