version: '3'
services:

  wololo-backend:
    build: ../TP-TACS
    container_name: wololo-backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks: 
      - back-end
      - db
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=wololo-tacs
  wololo-frontend:
    build: .
    container_name: wololo-frontend
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    depends_on:
      - wololo-si
      - wololo-backend
    ports:
      - 80:80
    networks:
      - back-end
      - web-socket
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_ENV=production
      - REACT_APP_API_URL=wololo-backend
      - REACT_APP_API_PORT=8080
      - REACT_APP_SOCKET_URL=localhost
      - REACT_APP_SOCKET_PORT=8082
      - REACT_APP_MAPS_KEY=pk.eyJ1IjoidGVvbm5uIiwiYSI6ImNrZzAwY3RoMjBqbHAydXBpMHFyeXQ2bjYifQ.aZZR74OETObsUi2tCtNbWg
  wololo-si:
    build: ./WololoSI
    container_name: wololo-si
    networks:
      - back-end
    ports: 
      - 8082:8082
    networks: 
      - web-socket
  mongodb:
    image: 'mongo'
    container_name: 'mongo-container'
    environment: 
        - MONGO_INITDB_DATABASE=wololo-tacs
    volumes:
      - ../TP-TACS/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports: 
        - '27017-27019:27017-27019'
    networks: 
        - db

networks:
  web-socket:
  db:
  # front-end: quizas despues la necesitemos para la interaccion con el usuario
  back-end:
