import React from 'react';
import { Modal } from 'rsuite';
import { Button } from 'rsuite';
import 'rsuite/dist/styles/rsuite-default.css';
import {connect, useDispatch, useSelector} from "react-redux";
import {CardBody} from "reactstrap";

class TownModal extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            backdrop: true,
        };
        this.close = this.close.bind(this);
    }
    close() {
        this.setState({ show: false });
    }
    render() {
        const { backdrop } = this.state;
        console.log("lo muestro", this.props.display)
        const town = this.props.town
        return (
            <div className="modal-container">

                <Modal backdrop={backdrop} show={this.props.display} onHide={this.close}>
                    <Modal.Header>
                        <Modal.Title>{town.name} stats</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                        <p> Coordinates; LATITUDE: {town.coordinates.lat}, LONGITUDE {town.coordinates.lon}</p>
                        <p> Gauchos Generated By Defense: {town.gauchosGeneratedByDefense}</p>
                        <p> Gauchos Generated By Production: {town.gauchosGeneratedByProduction}</p>
                        <p> Quantity of gauchos: {town.gauchos}</p>
                        {/*<CardText>Owner: {town.ownerId}</CardText>*/}
                        {/*<CardText>Coordinates: LATITUDE {town.coordinates.lat}, LONGITUDE {town.coordinates.lon}</CardText>*/}
                        {/*<CardText>gauchos quantity: {town.gauchos}</CardText>*/}
                    </Modal.Body>
                    <Modal.Footer>
                        <Button onClick={this.props.close} appearance="primary">
                            Ok
                        </Button>
                        <Button onClick={this.props.close} appearance="subtle">
                            Cancel
                        </Button>
                    </Modal.Footer>
                </Modal>
            </div>
        );
    }
}

export default TownModal;